name: hivefy
description: "A spotiify like Flutter App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">3.7.2 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  package_info_plus:
  dynamic_color:
  flashy_tab_bar2:
  flutter_riverpod:
  iconly:
  cached_network_image:
  shimmer:
  app_links:
  http:
  dart_des:
  html:
  html_unescape:
  just_audio:
  audio_session:
  rxdart:
  figma_squircle:
  hive:
  hive_flutter:
  marquee:
  page_transition:
  readmore:
  flutter_swipe_action_cell:
  toastification:
  audio_service:
  just_audio_background:
  drag_and_drop_lists:
  share_plus:
  dio:
  path_provider:
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
  flutter_lints: ^5.0.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: SpotifyMix
      fonts:
        - asset: assets/fonts/SpotifyMix-Thin.ttf
          weight: 100
        - asset: assets/fonts/SpotifyMix-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/SpotifyMix-Light.ttf
          weight: 300
        - asset: assets/fonts/SpotifyMix-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/SpotifyMix-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpotifyMix-RegularItalic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/SpotifyMix-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpotifyMix-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/SpotifyMix-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpotifyMix-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/SpotifyMix-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/SpotifyMix-ExtraboldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/SpotifyMix-Black.ttf
          weight: 900
        - asset: assets/fonts/SpotifyMix-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/SpotifyMix-Ultra.ttf
          weight: 900
        - asset: assets/fonts/SpotifyMix-UltraItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/logo.png"
  adaptive_icon_foreground: "assets/radio.png"
  adaptive_icon_background: "#1DDA63"
  adaptive_icon_monochrome: "assets/radio.png"
  adaptive_icon_foreground_inset: 24
